Fix installation and organize notebooks (#11)
* Organize notebooks and fix installation

* Try different keras version

* Roll back changes

* Try setting both keras and tf versions

* Another combination

* Add model conversion to setup and remove specific versioning

* change order of operations on setup

* add numpy explicitly

* reset changes

* Implement console script for setup

* move code into mads olsen support

* test out new CI

* try setup at different location

* finish setup before export

* see folders within ci

* search through all possible locations of pisces

* clean up ci

* add possibility of editable install

* add user site-packages directory

* allow for keras model difference only

* fix typo

* final cleanup

* simplify pisces_setup model save path

* remove deprecated use of importlib path

* minor updates

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,10 +1,92 @@
 name: CI
-on:  [workflow_dispatch, pull_request, push]
+on:
+  workflow_dispatch:
+    inputs:
+      pre:
+        description: 'Install prerelease nbdev/execnb from master?'
+        required: false
+        default: ''
+      version:
+        description: 'Version of python to set up'
+        required: false
+        default: '3.10'
+      skip_test:
+        description: 'Skip tests?'
+        required: false
+        default: ''
+      flags:
+        description: 'Space separated list of nbdev test flags to run that are normally ignored'
+        required: false
+        default: ''
+      torch_cpu:
+        description: "Install PyTorch CPU instead of PyTorch Cuda.  Has no effect if PyTorch isn't a requirement.  Enabled by defaut."
+        required: false
+        default: 'true'
+  push:
+  pull_request:
 
 jobs:
   test:
     runs-on: ubuntu-latest
     steps:
-      - uses: fastai/workflows/nbdev-ci@master
-        with:
-          version: '3.10'
+        - uses: actions/checkout@v3
+        - uses: actions/setup-python@v4
+          with:
+            python-version: ${{ inputs.version }}
+            cache: "pip"
+            cache-dependency-path: settings.ini
+        - name: Test with nbdev
+          env:
+            USE_PRE: ${{ inputs.pre }}
+            SKIP_TEST: ${{ inputs.skip_test }}
+            FLAGS: ${{ inputs.flags }}
+            TORCH_CPU: "${{ inputs.torch_cpu }}"
+          shell: bash
+          run: |
+            set -ux
+            python -m pip install --upgrade pip
+            if [ $USE_PRE ]; then
+              pip install -U git+https://github.com/fastai/fastcore.git
+              pip install -U git+https://github.com/fastai/ghapi.git
+              pip install -U git+https://github.com/fastai/execnb.git
+              pip install -U git+https://github.com/fastai/nbdev.git
+            else
+              pip install -U nbdev
+            fi
+            echo "Doing editable install..."
+            if [ $TORCH_CPU ]; then
+              test -f setup.py && pip install -e ".[dev]" --extra-index-url https://download.pytorch.org/whl/cpu/torch_stable.html
+            else
+              test -f setup.py && pip install -e ".[dev]"
+            fi
+            echo "Check we are starting with clean git checkout"
+            if [[ `git status --porcelain -uno` ]]; then
+              git diff
+              echo "git status is not clean"
+              false
+            fi
+            echo "Trying to strip out notebooks"
+            nbdev_clean
+            echo "Check that strip out was unnecessary"
+            git status -s # display the status to see which nbs need cleaning up
+            if [[ `git status --porcelain -uno` ]]; then
+              git status -uno
+              echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
+              echo -e "This error can also happen if you are using an older version of nbdev relative to what is in CI.  Please try to upgrade nbdev with the command `pip install -U nbdev`"
+              false
+            fi
+            echo "Finish pisces setup"
+            pisces_setup
+            nbdev_export
+            if [[ `git status --porcelain -uno` ]]; then
+              # allow changes only on pisces/cached_models/mo_resunet.keras
+              if [[ `git status --porcelain -uno | grep -v "cached_models/mo_resunet.keras"` ]]; then
+                echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
+                git status -uno
+                git diff
+                exit 1;
+              fi
+            fi
+            if [ ! $SKIP_TEST ]; then
+              nbdev_test --flags "$FLAGS"
+            fi
